<?php /* Smarty version Smarty-3.1.19, created on 2015-03-20 13:29:51
         compiled from "C:\xampp2\htdocs\prestashop_1.6.0.12\prestashop\admin\themes\default\css\overrides.css" */ ?>
<?php /*%%SmartyHeaderCode:29835550c12bfe11941-80704322%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '4ab6abaa55661ad1bca67d3324bc239d870efa07' => 
    array (
      0 => 'C:\\xampp2\\htdocs\\prestashop_1.6.0.12\\prestashop\\admin\\themes\\default\\css\\overrides.css',
      1 => 1424703476,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '29835550c12bfe11941-80704322',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.19',
  'unifunc' => 'content_550c12bfe11944_40394449',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_550c12bfe11944_40394449')) {function content_550c12bfe11944_40394449($_smarty_tpl) {?>/* This stylesheet should be used to add your custom styles to the back-office without using the Sass sources. It will be loaded after all the default styles. 
You should NOT edit any other exisiting back-office CSS file manually: they are generated by the Sass preprocessor: http://www.sass-lang.com/ . */<?php }} ?>
