<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['js_files'] = array (
array('jQuery/jquery'),
array('jQuery/jquery.measure'),
array('jQuery/jquery.place'),
array('jQuery/jquery.pulse'),
array('jQuery/jquery.mask'),
array('jQuery/jquery.loading'),
array('jQuery/jquery.facebox'),
#array('jQuery/jquery.tipsy'),
array('ext/adapter/jquery/ext-jquery-adapter', 'ext/adapter/jquery/ext-jquery-adapter-debug'),
array('ext/ext-all', 'ext/ext-all-debug'),
#array('ext-fixes'),
array('ext/locale/ext-lang-es'),
array('tiny_mce/tiny_mce', 'tiny_mce/tiny_mce_src'),
array('tiny_mce/langs/es', 'tiny_mce/langs/es'),
array('ux/FileUploadField'),
array('ux/miframe'),
array('ux/Spinner'),
array('ux/SpinnerStrategy'),
array('ux/TreeCheckNode'),
array('ux/data-view-plugins'),
array('ux/GroupSummary'),
array('ux/HistoryClearableComboBox'),
array('ux/Ext.ux.TDGi.MenuKeyTrigger'),
array('ux/Ext.ux.TinyMCE'),
array('ux/StatusBar'),
array('ux/ColumnTree'),
array('ux/DateTimeEx'),
array('ux/CheckColumn'),
#array('ux/iframe'),
array('ux/SuperBoxSelect'),
array('ux/autocomplete'),
array('ux/browsebutton'),
array('ux/Ext.ux.TextID'),
array('ux/Ext.ux.CellToolTips'),
array('ux/Ext.ux.ISBN'),
array('ux/Ext.ux.SearchCombo'),
array('ux/Ext.ux.DateTime'),
array('ux/Ext.ux.HtmlEditor.Plugins'),
array('ux/StartMenu'),
array('ux/Portal'),
array('ux/PortalColumn'),
array('ux/Portlet'),
array('ux/TreeGridSorter'),
array('ux/TreeGridColumnResizer'),
array('ux/TreeGridNodeUI'),
array('ux/TreeGridLoader'),
array('ux/TreeGridColumns'),
array('ux/TreeGrid'),
#array('plupload/js/plupload.full.min', 'plupload/js/plupload.full.min'),
#array('ux/ext.ux.plupload'),
#array('ux/TabScrollerMenu'),
#array('ux/ToolbarDroppable'),
#array('ux/ToolbarReorderer'),
#array('ux/Reorderer'),
array('ux/Ext.ux.IconCombo'),
array('zeroclipboard/ZeroClipboard'),
array('ux/Ext.ux.MessageWindow'),
array('ux/slidingtabs'),
array('ux/TabCloseMenu'),
array('ux/Ext.ux.form.FileUploadField'),
array('ux/Ext.ux.XHRUpload'),
array('ux/swfupload'),
array('ux/Ext.ux.AwesomeUploaderLocalization'),
array('ux/AwesomeUploader'),
array('jsDate'),
array('gridToExcel'),
array('functions'),
array('documentos'),
array('chat'),
);

$config['css_files'] = array(
array('ext-all', 'ext'),
array('MMCal'),
#array('tipsy'),
array('datepickerplus'),
array('file-upload'),
array('TreeCheckNode'),
array('statusbar'),
array('superboxselect'),
array('column-tree'),
array('Spinner'),
array('TreeGrid'),
array('facebox'),
array('Ext.ux.form.FileUploadField'),
array('AwesomeUploader'),
array('AwesomeUploaderProgressBar'),
#array('ext.ux.plupload'),
array('style','main'),
array('icons','main'),
array('forms','main'),
array('bubbles', 'main'),
array('startmenu','main'),	
);


